export const PALACE_FOYER_WIDTH = 48;
export const PALACE_FOYER_DEPTH = 34;
export const PALACE_FOYER_HEIGHT = 5.2;
export const PALACE_FOYER_RECESS_HEIGHT = 2.1;
export const PALACE_AUDITORIUM_WIDTH = 34;
export const PALACE_AUDITORIUM_DEPTH = 24;
export const PALACE_AUDITORIUM_CENTRE_X = -5;
export const PALACE_AUDITORIUM_CENTRE_Z = -4;
export const PALACE_AUDITORIUM_EAVE_Y = 13.9;
export const PALACE_APEX_Y = 15.625;
export const PALACE_ROOF_RIDGE_HALF_LENGTH = 10;

export const PALACE_FOYER_HALF_WIDTH = PALACE_FOYER_WIDTH / 2;
export const PALACE_FOYER_HALF_DEPTH = PALACE_FOYER_DEPTH / 2;
export const PALACE_HALL_HALF_WIDTH = PALACE_AUDITORIUM_WIDTH / 2;
export const PALACE_HALL_HALF_DEPTH = PALACE_AUDITORIUM_DEPTH / 2;
export const PALACE_HALL_LEFT = PALACE_AUDITORIUM_CENTRE_X
  - PALACE_HALL_HALF_WIDTH;
export const PALACE_HALL_RIGHT = PALACE_AUDITORIUM_CENTRE_X
  + PALACE_HALL_HALF_WIDTH;
export const PALACE_HALL_REAR = PALACE_AUDITORIUM_CENTRE_Z
  - PALACE_HALL_HALF_DEPTH;
export const PALACE_HALL_FRONT = PALACE_AUDITORIUM_CENTRE_Z
  + PALACE_HALL_HALF_DEPTH;
