import type { CinematicFlyoverDefinition } from "./cinematicFlyoverPlan";

const stillRoot = "/games/make-a-mess/flyovers/grand-terminal";

export const grandTerminalFlyover: CinematicFlyoverDefinition = {
  id: "the-last-departure",
  title: "The Last Departure",
  locationLabel: "GRAND TERMINAL",
  storyLabel: "A TERMINAL STORY",
  backLabel: "BACK TO TERMINAL",
  durationSeconds: 110,
  fileName: "grand-terminal-the-last-departure",
  keyframes: [
    { at: 0, position: [0, 18, 88], lookAt: [0, 11, 34], fov: 48, timeOfDay: "day" },
    { at: 0.08, position: [-30, 11, 63], lookAt: [0, 10, 34], fov: 51, timeOfDay: "day" },
    { at: 0.16, position: [14, 7, 49], lookAt: [0, 10, 34], fov: 52, timeOfDay: "day" },
    { at: 0.24, position: [0, 4.2, 36.5], lookAt: [0, 6, 17], fov: 58, timeOfDay: "day" },
    { at: 0.32, position: [-8, 7, 26], lookAt: [0, 8.5, 11.4], fov: 55, timeOfDay: "day" },
    { at: 0.4, position: [6, 8, 19], lookAt: [0, 8.5, 11.4], fov: 50, timeOfDay: "day" },
    { at: 0.48, position: [0, 6.5, 7], lookAt: [-4, 5, -22], fov: 57, timeOfDay: "day" },
    { at: 0.56, position: [23, 18, -5], lookAt: [0, 7, -34], fov: 54, timeOfDay: "day" },
    { at: 0.63, position: [-17, 6, -49], lookAt: [-9, 3.5, -40], fov: 49, timeOfDay: "sunset" },
    { at: 0.7, position: [-14, 4, -34], lookAt: [-9, 3.4, -38], fov: 56, timeOfDay: "sunset" },
    { at: 0.77, position: [3, 6, -23], lookAt: [9, 3, -43], fov: 55, timeOfDay: "sunset" },
    { at: 0.84, position: [42, 28, -60], lookAt: [0, 8, -14], fov: 52, timeOfDay: "sunset" },
    { at: 0.91, position: [64, 42, 4], lookAt: [0, 8, -14], fov: 50, timeOfDay: "sunset" },
    { at: 0.96, position: [20, 54, 68], lookAt: [0, 8, -14], fov: 48, timeOfDay: "sunset" },
    { at: 1, position: [-45, 46, 55], lookAt: [0, 8, -14], fov: 49, timeOfDay: "sunset" },
  ],
  chapters: [
    {
      id: "promise",
      from: 0.015,
      to: 0.125,
      kicker: "THE LAST DEPARTURE",
      title: "Every station begins with a promise: somewhere else.",
      body: "Here, the promise was built in brick, glass and brass.",
      align: "left",
      captureAt: 0.075,
      stillImage: `${stillRoot}/text/01-promise.png`,
      cleanStillImage: `${stillRoot}/clean/01-promise.png`,
    },
    {
      id: "clock",
      from: 0.13,
      to: 0.225,
      title: "The clock does not hurry.",
      body: "Everyone beneath it does.",
      align: "right",
      captureAt: 0.185,
      stillImage: `${stillRoot}/text/02-clock.png`,
      cleanStillImage: `${stillRoot}/clean/02-clock.png`,
    },
    {
      id: "concourse",
      from: 0.245,
      to: 0.36,
      title: "A thousand departures become one room.",
      body: "For a moment, strangers agree on the same direction.",
      align: "left",
      captureAt: 0.31,
      stillImage: `${stillRoot}/text/03-concourse.png`,
      cleanStillImage: `${stillRoot}/clean/03-concourse.png`,
    },
    {
      id: "board",
      from: 0.365,
      to: 0.46,
      title: "The board remembers towns the rails no longer reach.",
      body: "Their names still make the room feel larger.",
      align: "right",
      captureAt: 0.42,
      stillImage: `${stillRoot}/text/04-board.png`,
      cleanStillImage: `${stillRoot}/clean/04-board.png`,
    },
    {
      id: "shed",
      from: 0.47,
      to: 0.59,
      title: "Under glass, distance becomes architecture.",
      body: "Iron holds the sky high enough for longing to pass beneath it.",
      align: "left",
      captureAt: 0.545,
      stillImage: `${stillRoot}/text/05-shed.png`,
      cleanStillImage: `${stillRoot}/clean/05-shed.png`,
    },
    {
      id: "engine",
      from: 0.595,
      to: 0.71,
      title: "This engine once made the horizon move.",
      body: "Now the building travels for it.",
      align: "right",
      captureAt: 0.66,
      stillImage: `${stillRoot}/text/06-engine.png`,
      cleanStillImage: `${stillRoot}/clean/06-engine.png`,
    },
    {
      id: "memory",
      from: 0.715,
      to: 0.835,
      title: "What remains is not silence.",
      body: "It is every journey waiting to be imagined again.",
      align: "left",
      captureAt: 0.78,
      stillImage: `${stillRoot}/text/07-memory.png`,
      cleanStillImage: `${stillRoot}/clean/07-memory.png`,
    },
    {
      id: "terminal",
      from: 0.855,
      to: 0.995,
      kicker: "THE LAST DEPARTURE",
      title: "GRAND TERMINAL",
      align: "center",
      textScale: "hero",
      captureAt: 0.945,
      stillImage: `${stillRoot}/text/08-grand-terminal.png`,
      cleanStillImage: `${stillRoot}/clean/08-grand-terminal.png`,
    },
  ],
};
