import type { CinematicFlyoverDefinition } from "./cinematicFlyoverPlan";

export const islandAirportFlyover: CinematicFlyoverDefinition = {
  id: "island-approach",
  title: "Island Approach",
  locationLabel: "ISLAND AIRPORT",
  storyLabel: "A SHORT-FIELD STORY",
  backLabel: "BACK TO AIRPORT",
  durationSeconds: 76,
  fileName: "island-airport-approach",
  keyframes: [
    { at: 0, position: [-137, 46, -68], lookAt: [-42, 1, -20], fov: 47, timeOfDay: "day" },
    { at: 0.12, position: [-94, 19, -48], lookAt: [-32, 1, -22], fov: 52, timeOfDay: "day" },
    { at: 0.24, position: [-38, 9, -37], lookAt: [19, 2, -16], fov: 55, timeOfDay: "day" },
    { at: 0.36, position: [3, 15, -15], lookAt: [9, 3.5, 18], fov: 51, timeOfDay: "day" },
    { at: 0.42, position: [45, 14, 2], lookAt: [9, 3.5, 20], fov: 53, timeOfDay: "day" },
    { at: 0.49, position: [42, 9, 41], lookAt: [8, 3.2, 20], fov: 54, timeOfDay: "day" },
    { at: 0.535, position: [4.75, 4.8, 38], lookAt: [5, 2.5, 20], fov: 58, timeOfDay: "day" },
    { at: 0.575, position: [4.75, 2.7, 33.4], lookAt: [5, 2.3, 18], fov: 61, timeOfDay: "day" },
    { at: 0.64, position: [5, 2.5, 25], lookAt: [11, 2.1, 14], fov: 63, timeOfDay: "day" },
    { at: 0.675, position: [4.75, 2.7, 33.4], lookAt: [8, 2.5, 20], fov: 61, timeOfDay: "day" },
    { at: 0.71, position: [4.75, 3.5, 37], lookAt: [8, 2.5, 20], fov: 58, timeOfDay: "day" },
    { at: 0.76, position: [25, 4.5, 39], lookAt: [20, 4, 20], fov: 55, timeOfDay: "sunset" },
    { at: 0.82, position: [73, 26, 42], lookAt: [39, 8, 16], fov: 49, timeOfDay: "sunset" },
    { at: 0.88, position: [93, 29, 13], lookAt: [18, 3, -5], fov: 51, timeOfDay: "sunset" },
    { at: 0.95, position: [53, 44, -62], lookAt: [0, 2, -10], fov: 48, timeOfDay: "sunset" },
    { at: 1, position: [-72, 55, 44], lookAt: [5, 2, -8], fov: 50, timeOfDay: "sunset" },
  ],
  chapters: [
    {
      id: "shoreline",
      from: 0.02,
      to: 0.18,
      kicker: "ISLAND APPROACH",
      title: "A runway drawn to the length of the land.",
      body: "Short thresholds, open water and no wasted ground.",
      align: "left",
      captureAt: 0.08,
    },
    {
      id: "airside",
      from: 0.2,
      to: 0.365,
      title: "Runway, taxiway and apron work as one compact field.",
      align: "right",
      captureAt: 0.3,
    },
    {
      id: "terminal",
      from: 0.37,
      to: 0.69,
      title: "The whole town fits beneath eight structural bays.",
      body: "Check-in, security, gates and baggage remain walkable end to end.",
      align: "left",
      captureAt: 0.575,
    },
    {
      id: "tower",
      from: 0.75,
      to: 0.9,
      title: "Complete airfield systems.",
      body: "Tower, rescue station, maintenance and fuel keep the runway alive.",
      align: "right",
      captureAt: 0.83,
    },
    {
      id: "departure",
      from: 0.92,
      to: 0.995,
      kicker: "SHORT FIELD / FULL AIRPORT",
      title: "ISLAND AIRPORT",
      align: "center",
      textScale: "hero",
      captureAt: 0.96,
    },
  ],
};
