import type { CinematicFlyoverDefinition } from "./cinematicFlyoverPlan";

export const vikingVillageFlyover: CinematicFlyoverDefinition = {
  id: "they-chose-to-stay",
  title: "They Chose to Stay",
  locationLabel: "VIKING VILLAGE",
  storyLabel: "A VILLAGE STORY",
  backLabel: "BACK TO VILLAGE",
  durationSeconds: 92,
  fileName: "viking-village-they-chose-to-stay",
  keyframes: [
    { at: 0, position: [0, 19, 84], lookAt: [0, 4, 47], fov: 48, timeOfDay: "sunset" },
    { at: 0.09, position: [-8, 8, 59], lookAt: [0, 3.5, 47], fov: 52, timeOfDay: "sunset" },
    { at: 0.17, position: [-1.6, 4.4, 45], lookAt: [0, 2.6, 29], fov: 58, timeOfDay: "day" },
    { at: 0.27, position: [-4, 5.2, 29], lookAt: [-10, 1.8, 13], fov: 55, timeOfDay: "day" },
    { at: 0.36, position: [-16, 7.5, 20], lookAt: [-10, 1.5, 13], fov: 52, timeOfDay: "day" },
    { at: 0.45, position: [-22, 5.2, -1], lookAt: [-28, 1.7, -12], fov: 54, timeOfDay: "day" },
    { at: 0.54, position: [-28, 3.1, -5], lookAt: [-28, 1.5, -15], fov: 60, timeOfDay: "day" },
    { at: 0.63, position: [-12, 5.5, -1], lookAt: [0, 3.2, -17], fov: 53, timeOfDay: "sunset" },
    { at: 0.71, position: [0, 3.6, -3.8], lookAt: [0, 2.6, -18], fov: 57, timeOfDay: "sunset" },
    { at: 0.8, position: [0, 2.8, -14], lookAt: [0, 2.7, -27], fov: 59, timeOfDay: "sunset" },
    { at: 0.87, position: [0, 3.3, -23], lookAt: [0, 3, -29], fov: 50, timeOfDay: "night" },
    { at: 0.94, position: [9, 14, -39], lookAt: [0, 4.5, -17], fov: 52, timeOfDay: "night" },
    { at: 1, position: [34, 28, -67], lookAt: [0, 3.5, -17], fov: 48, timeOfDay: "night" },
  ],
  chapters: [
    {
      id: "arrival",
      from: 0.015,
      to: 0.13,
      kicker: "THEY CHOSE TO STAY",
      title: "From here, it still looks temporary.",
      body: "But inside the palisade, someone has already planned for another winter.",
      align: "left",
      captureAt: 0.085,
      stillImage: "/games/make-a-mess/flyovers/viking-village/01-arrival.png",
    },
    {
      id: "watch",
      from: 0.15,
      to: 0.235,
      title: "The village wakes before its guards do.",
      align: "right",
      captureAt: 0.205,
      stillImage: "/games/make-a-mess/flyovers/viking-village/02-watch.png",
    },
    {
      id: "paths",
      from: 0.27,
      to: 0.39,
      title: "No hall holds this place together.",
      body: "Water, fire and footsteps do.",
      align: "left",
      captureAt: 0.335,
      stillImage: "/games/make-a-mess/flyovers/viking-village/03-paths.png",
    },
    {
      id: "future-house",
      from: 0.43,
      to: 0.565,
      title: "By winter, another family will live here.",
      body: "For now, the wind passes through their future walls.",
      align: "right",
      captureAt: 0.515,
      stillImage: "/games/make-a-mess/flyovers/viking-village/04-future-house.png",
    },
    {
      id: "work",
      from: 0.585,
      to: 0.685,
      title: "Beyond the palisade, war feels distant.",
      body: "Work never does.",
      align: "left",
      captureAt: 0.645,
      stillImage: "/games/make-a-mess/flyovers/viking-village/05-work.png",
    },
    {
      id: "hall",
      from: 0.71,
      to: 0.845,
      title: "At dusk, scattered yards become one house.",
      align: "center",
      captureAt: 0.79,
      stillImage: "/games/make-a-mess/flyovers/viking-village/06-hall.png",
    },
    {
      id: "fire",
      from: 0.875,
      to: 0.985,
      title: "Their fire can be seen for miles.",
      body: "That is why the gate is never unwatched.",
      align: "right",
      captureAt: 0.945,
      stillImage: "/games/make-a-mess/flyovers/viking-village/07-fire.png",
    },
  ],
};
